// Sayt matnlari — uch tilda (uz / ru / en).
// `data-i18n="kalit"` — oddiy matn, `data-i18n-html` — HTML, `data-i18n-ph` — placeholder.
var I18N = {
  uz: {
    navWork: "Loyihalar",
    navAbout: "Men haqimda",
    navContact: "Aloqa",
    role: "AI Engineer · Frontend Developer",
    heroLead: "Sun'iy intellekt qo'shilgan veb-ilovalar, ovozli yordamchilar va Telegram botlar yarataman. Ichida LLM, Whisper va real API'lar, tashqarida tez va toza interfeys.",
    available: "Yangi loyihalar uchun ochiqman",
    ctaWork: "Loyihalarni ko'rish",
    ctaCv: "CV yuklab olish",
    hint: "Sichqonchani yurgizing — portret 3D",
    workTitle: "Tanlangan ishlar",
    workSub: "AI va frontend loyihalarim. Har birining kodi GitHub'da ochiq.",
    linkDemo: "Live demo",
    linkCode: "Kod",
    aboutTitle: "Men haqimda",
    about1: "Men Saydullayev Xojiakbar, Angrendan AI engineer va frontend dasturchiman. Frontend'dan boshladim: HTML, CSS va JavaScript'dan React va Next.js'gacha. Keyin LLM agentlar, nutqni tanish va avtomatlashtirish bilan ishlay boshladim.",
    about2: "Eng katta mijoz ishim — Angren 4-son Texnikumining rasmiy sayti: uch tilli, onlayn qabul tizimi, admin panel va Telegram bildirishnomalari bilan. Hozir u VPS serverda ishlab turibdi.",
    expTitle: "Tajriba",
    exp1Title: "AI loyihalar",
    exp1Text: "O'zbek tilini tushunadigan ovozli agent, audio'dan konspekt tuzuvchi ilova, 24/7 ishlaydigan Telegram botlar.",
    exp2Title: "Birinchi real mijoz",
    exp2Text: "Angren 4-son Texnikumi sayti — noldan qurib, VPS serverga joyladim.",
    exp3Title: "Frontend",
    exp3Text: "HTML, CSS, JavaScript, React — kurs va amaliy loyihalar.",
    skillsTitle: "Ko'nikmalar",
    skAi: "AI",
    skFront: "Frontend",
    skBack: "Backend va vositalar",
    procTitle: "Qanday ishlayman",
    proc1Title: "Gaplashamiz",
    proc1Text: "Maqsad, muddat va byudjetni aniqlaymiz.",
    proc2Title: "Reja",
    proc2Text: "Tuzilma va dizaynni kod yozishdan oldin kelishamiz.",
    proc3Title: "Ishlab chiqish",
    proc3Text: "Har bosqichda ishlaydigan versiyani ko'rsataman.",
    proc4Title: "Topshirish",
    proc4Text: "Deploy, tekshiruv va qo'llanma bilan topshiraman.",
    contactTitle: "Loyihangiz bormi?",
    contactSub: "Qisqacha yozing — 24 soat ichida javob beraman.",
    cfName: "Ism",
    cfNamePh: "Ismingiz",
    cfContact: "Email yoki Telegram",
    cfContactPh: "siz@example.com yoki @username",
    cfMsg: "Xabar",
    cfMsgPh: "Loyiha haqida qisqacha...",
    cfSend: "Yuborish",
    cfSending: "Yuborilmoqda...",
    cfOk: "Rahmat! Xabaringiz yuborildi.",
    cfErr: "Yuborilmadi. Iltimos, to'g'ridan-to'g'ri email yoki Telegram orqali yozing.",
    footerTop: "Tepaga ↑"
  },
  ru: {
    navWork: "Проекты",
    navAbout: "Обо мне",
    navContact: "Контакт",
    role: "AI Engineer · Frontend Developer",
    heroLead: "Создаю веб-приложения с искусственным интеллектом, голосовых ассистентов и Telegram-ботов. Внутри — LLM, Whisper и реальные API, снаружи — быстрый и чистый интерфейс.",
    available: "Открыт для новых проектов",
    ctaWork: "Смотреть проекты",
    ctaCv: "Скачать CV",
    hint: "Подвигайте курсором — портрет в 3D",
    workTitle: "Избранные работы",
    workSub: "Мои проекты в ИИ и frontend. Код каждого открыт на GitHub.",
    linkDemo: "Live demo",
    linkCode: "Код",
    aboutTitle: "Обо мне",
    about1: "Я Сайдуллаев Хожиакбар — AI engineer и frontend-разработчик из Ангрена. Начинал с frontend: от HTML, CSS и JavaScript до React и Next.js. Затем занялся LLM-агентами, распознаванием речи и автоматизацией.",
    about2: "Мой главный клиентский проект — официальный сайт Ангренского техникума №4: трёхъязычный, с онлайн-приёмом, админ-панелью и уведомлениями в Telegram. Сейчас он работает на VPS.",
    expTitle: "Опыт",
    exp1Title: "Проекты в ИИ",
    exp1Text: "Голосовой агент, понимающий узбекский язык, приложение для конспектов из аудио, Telegram-боты 24/7.",
    exp2Title: "Первый реальный клиент",
    exp2Text: "Сайт Ангренского техникума №4 — построил с нуля и развернул на VPS.",
    exp3Title: "Frontend",
    exp3Text: "HTML, CSS, JavaScript, React — курс и практические проекты.",
    skillsTitle: "Навыки",
    skAi: "ИИ",
    skFront: "Frontend",
    skBack: "Backend и инструменты",
    procTitle: "Как я работаю",
    proc1Title: "Обсуждение",
    proc1Text: "Определяем цель, сроки и бюджет.",
    proc2Title: "План",
    proc2Text: "Согласуем структуру и дизайн до написания кода.",
    proc3Title: "Разработка",
    proc3Text: "На каждом этапе показываю рабочую версию.",
    proc4Title: "Сдача",
    proc4Text: "Деплой, проверка и инструкция.",
    contactTitle: "Есть проект?",
    contactSub: "Напишите коротко — отвечу в течение 24 часов.",
    cfName: "Имя",
    cfNamePh: "Ваше имя",
    cfContact: "Email или Telegram",
    cfContactPh: "you@example.com или @username",
    cfMsg: "Сообщение",
    cfMsgPh: "Коротко о проекте...",
    cfSend: "Отправить",
    cfSending: "Отправка...",
    cfOk: "Спасибо! Сообщение отправлено.",
    cfErr: "Не удалось отправить. Напишите напрямую на email или в Telegram.",
    footerTop: "Наверх ↑"
  },
  en: {
    navWork: "Work",
    navAbout: "About",
    navContact: "Contact",
    role: "AI Engineer · Frontend Developer",
    heroLead: "I build AI-powered web apps, voice assistants and Telegram bots. LLMs, Whisper and real APIs on the inside, with a fast, clean interface on the outside.",
    available: "Available for new projects",
    ctaWork: "View work",
    ctaCv: "Download CV",
    hint: "Move your cursor — the portrait is 3D",
    workTitle: "Selected work",
    workSub: "AI and frontend projects. The code for each one is on GitHub.",
    linkDemo: "Live demo",
    linkCode: "Code",
    aboutTitle: "About",
    about1: "I'm Xojiakbar Saydullayev, an AI engineer and frontend developer from Angren, Uzbekistan. I started with frontend, going from HTML, CSS and JavaScript to React and Next.js, then moved into LLM agents, speech recognition and automation.",
    about2: "My main client project is the official website of Angren Technical College No. 4. It's trilingual, with online admissions, an admin panel and Telegram notifications, and it runs on a VPS today.",
    expTitle: "Experience",
    exp1Title: "AI projects",
    exp1Text: "A voice agent that understands Uzbek, an app that turns audio into notes, and Telegram bots that run 24/7.",
    exp2Title: "First real client",
    exp2Text: "Angren Technical College No. 4 website, built from scratch and deployed to a VPS.",
    exp3Title: "Frontend",
    exp3Text: "HTML, CSS, JavaScript and React, through a course and hands-on projects.",
    skillsTitle: "Skills",
    skAi: "AI",
    skFront: "Frontend",
    skBack: "Backend & tools",
    procTitle: "How I work",
    proc1Title: "Talk",
    proc1Text: "We agree on the goal, timeline and budget.",
    proc2Title: "Plan",
    proc2Text: "Structure and design are settled before any code.",
    proc3Title: "Build",
    proc3Text: "You see a working version at every stage.",
    proc4Title: "Deliver",
    proc4Text: "Deployed, tested and handed over with a short guide.",
    contactTitle: "Have a project?",
    contactSub: "Send a short message and I'll reply within 24 hours.",
    cfName: "Name",
    cfNamePh: "Your name",
    cfContact: "Email or Telegram",
    cfContactPh: "you@example.com or @username",
    cfMsg: "Message",
    cfMsgPh: "A few words about the project...",
    cfSend: "Send",
    cfSending: "Sending...",
    cfOk: "Thanks! Your message was sent.",
    cfErr: "It couldn't be sent. Please email me or message me on Telegram directly.",
    footerTop: "Back to top ↑"
  }
};
